### ISSUE TITLE
cant rename proyect

### ISSUE THREAD

**Issue by draczer01** [humhub/example-basic#1] opened 2021-04-06 03:13 UTC
Invalid Configuration – yii\base\InvalidConfigException
Unable to locate message source for category 'ExampleBasicModule.base'.

this happens after changing the variables on the documentation

**Comment by luke-** [comment] 2021-04-06 11:33
Can you please provide steps to reproduce?

**Comment by draczer01** [comment] 2021-04-07 07:57
sure, this is what I did:

mkdir myPlugin
cd myPlugin
git clone https://github.com/humhub/humhub-modules-example-basic.git .
rm .git -rf

then I modified the variables $newModuleId and $newNamespace. in docs/rewrite-module-id.php

```
$newModuleId = "formbuilder";
$newNamespace = 'coolSoft\humhub\modules\formbuilder';
```
changed to 
```
$newModuleId = "myPlugin";
$newNamespace = 'htdocs\humhub\modules\myPlugin';
```

and I have even tried to chage it to:

```
$newModuleId = "myPlugin";
$newNamespace = 'companyName\humhub\modules\myPlugin';
```

then I execute 
`php rewrite-module-id.php`
in the shell

im using the latest version of windows 10 and php

**Comment by luke-** [comment] 2021-04-09 10:28
@draczer01 This is probably due to the format of the module ID. it must be written in the kebab case. i.e. my-plugin.
I have added a hint here.

**Comment by draczer01** [comment] 2021-04-15 13:57
the issue Unable to locate message source for category 'ExampleBasicModule.base'. persists, also the plugin still apears as example basic in the enableing window

**Comment by luke-** [comment] 2021-04-16 09:50
What values did you use? Then I'll try to reproduce it for myself.

**Comment by draczer01** [comment] 2021-04-18 01:17
rpg-campaings

rpg\humhub\modules\rpg
and I tried renaming the proyect folder to rpg and rpg-campaings and got no changes what so ever

**Comment by luke-** [comment] 2021-04-19 11:05
Hmm cannot produce this.

1.) Create Module Repo

```
git clone git@github.com:humhub/example-basic.git rpg-campaings    
```
2.) Adjust `docs/rewrite-module-id.php`:
``` 
$newModuleId = "rgp-campaings";
$newNamespace = 'rpg\humhub\modules\rpg';
``` 
3.) Execute and Enable the Module

**Comment by luke-** [comment] 2021-04-19 11:12
@draczer01 Should be fixed now. Thank you for your help!

**Closed** 2021-04-19 11:12 UTC
